"""empty message

Revision ID: aee2f405c0a4
Revises: 1f53669c22ee
Create Date: 2020-12-11 20:04:57.095362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee2f405c0a4'
down_revision = '1f53669c22ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paygrade', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paygrade')
    )
    op.add_column('employees', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'grade_id')
    op.drop_table('grades')
    # ### end Alembic commands ###
